// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package providers

import (
	"context"

	"github.com/binarymatt/fence/gen/fence/v1"
	mock "github.com/stretchr/testify/mock"
)

// NewMockFenceProvider creates a new instance of MockFenceProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFenceProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFenceProvider {
	mock := &MockFenceProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFenceProvider is an autogenerated mock type for the FenceProvider type
type MockFenceProvider struct {
	mock.Mock
}

type MockFenceProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFenceProvider) EXPECT() *MockFenceProvider_Expecter {
	return &MockFenceProvider_Expecter{mock: &_m.Mock}
}

// IsAllowed provides a mock function for the type MockFenceProvider
func (_mock *MockFenceProvider) IsAllowed(ctx context.Context, principal *fencev1.UID, action *fencev1.UID, resource *fencev1.UID) (*fencev1.IsAllowedResponse, error) {
	ret := _mock.Called(ctx, principal, action, resource)

	if len(ret) == 0 {
		panic("no return value specified for IsAllowed")
	}

	var r0 *fencev1.IsAllowedResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *fencev1.UID, *fencev1.UID, *fencev1.UID) (*fencev1.IsAllowedResponse, error)); ok {
		return returnFunc(ctx, principal, action, resource)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *fencev1.UID, *fencev1.UID, *fencev1.UID) *fencev1.IsAllowedResponse); ok {
		r0 = returnFunc(ctx, principal, action, resource)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*fencev1.IsAllowedResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *fencev1.UID, *fencev1.UID, *fencev1.UID) error); ok {
		r1 = returnFunc(ctx, principal, action, resource)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFenceProvider_IsAllowed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsAllowed'
type MockFenceProvider_IsAllowed_Call struct {
	*mock.Call
}

// IsAllowed is a helper method to define mock.On call
//   - ctx context.Context
//   - principal *fencev1.UID
//   - action *fencev1.UID
//   - resource *fencev1.UID
func (_e *MockFenceProvider_Expecter) IsAllowed(ctx interface{}, principal interface{}, action interface{}, resource interface{}) *MockFenceProvider_IsAllowed_Call {
	return &MockFenceProvider_IsAllowed_Call{Call: _e.mock.On("IsAllowed", ctx, principal, action, resource)}
}

func (_c *MockFenceProvider_IsAllowed_Call) Run(run func(ctx context.Context, principal *fencev1.UID, action *fencev1.UID, resource *fencev1.UID)) *MockFenceProvider_IsAllowed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *fencev1.UID
		if args[1] != nil {
			arg1 = args[1].(*fencev1.UID)
		}
		var arg2 *fencev1.UID
		if args[2] != nil {
			arg2 = args[2].(*fencev1.UID)
		}
		var arg3 *fencev1.UID
		if args[3] != nil {
			arg3 = args[3].(*fencev1.UID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockFenceProvider_IsAllowed_Call) Return(isAllowedResponse *fencev1.IsAllowedResponse, err error) *MockFenceProvider_IsAllowed_Call {
	_c.Call.Return(isAllowedResponse, err)
	return _c
}

func (_c *MockFenceProvider_IsAllowed_Call) RunAndReturn(run func(ctx context.Context, principal *fencev1.UID, action *fencev1.UID, resource *fencev1.UID) (*fencev1.IsAllowedResponse, error)) *MockFenceProvider_IsAllowed_Call {
	_c.Call.Return(run)
	return _c
}

// Refresh provides a mock function for the type MockFenceProvider
func (_mock *MockFenceProvider) Refresh(context1 context.Context) error {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for Refresh")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFenceProvider_Refresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Refresh'
type MockFenceProvider_Refresh_Call struct {
	*mock.Call
}

// Refresh is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockFenceProvider_Expecter) Refresh(context1 interface{}) *MockFenceProvider_Refresh_Call {
	return &MockFenceProvider_Refresh_Call{Call: _e.mock.On("Refresh", context1)}
}

func (_c *MockFenceProvider_Refresh_Call) Run(run func(context1 context.Context)) *MockFenceProvider_Refresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFenceProvider_Refresh_Call) Return(err error) *MockFenceProvider_Refresh_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFenceProvider_Refresh_Call) RunAndReturn(run func(context1 context.Context) error) *MockFenceProvider_Refresh_Call {
	_c.Call.Return(run)
	return _c
}
