version: "3"
tasks:
  go:test:
    cmds:
      - go test ./... -cover
  proto:
    cmds:
      - buf lint
      - buf generate
  go:mocks:
    cmds:
      - mockery
  infra:plan:
    cmds:
      - cd terraform && terraform plan -var="container_image=registry.homelab.lan/fence-agent" -var="container_version={{.GIT_COMMIT}}"
    vars:
      GIT_COMMIT:
        sh: git log -n 1 --format=%h
  deploy:
    deps:
      - container:build
    cmds:
      - cd terraform && terraform apply -var="container_image=registry.homelab.lan/fence-agent" -var="container_version={{.GIT_COMMIT}}" -auto-approve
    vars:
      GIT_COMMIT:
        sh: git log -n 1 --format=%h
  container:build:
    cmds:
      - podman build -t fence-agent .
      - podman tag fence-agent registry.homelab.lan/fence-agent:{{.GIT_COMMIT}}
      - podman tag fence-agent registry.homelab.lan/fence-agent:latest
      - podman push registry.homelab.lan/fence-agent:latest
      - podman push registry.homelab.lan/fence-agent:{{.GIT_COMMIT}}
    vars:
      GIT_COMMIT:
        sh: git log -n 1 --format=%h
