// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"context"

	"github.com/binarymatt/fence/gen/fence/v1"
	"github.com/cedar-policy/cedar-go"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDataStore creates a new instance of MockDataStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDataStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDataStore {
	mock := &MockDataStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDataStore is an autogenerated mock type for the DataStore type
type MockDataStore struct {
	mock.Mock
}

type MockDataStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDataStore) EXPECT() *MockDataStore_Expecter {
	return &MockDataStore_Expecter{mock: &_m.Mock}
}

// addEntity provides a mock function for the type MockDataStore
func (_mock *MockDataStore) addEntity(ctx context.Context, entity *fencev1.Entity) error {
	ret := _mock.Called(ctx, entity)

	if len(ret) == 0 {
		panic("no return value specified for addEntity")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *fencev1.Entity) error); ok {
		r0 = returnFunc(ctx, entity)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDataStore_addEntity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'addEntity'
type MockDataStore_addEntity_Call struct {
	*mock.Call
}

// addEntity is a helper method to define mock.On call
//   - ctx context.Context
//   - entity *fencev1.Entity
func (_e *MockDataStore_Expecter) addEntity(ctx interface{}, entity interface{}) *MockDataStore_addEntity_Call {
	return &MockDataStore_addEntity_Call{Call: _e.mock.On("addEntity", ctx, entity)}
}

func (_c *MockDataStore_addEntity_Call) Run(run func(ctx context.Context, entity *fencev1.Entity)) *MockDataStore_addEntity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *fencev1.Entity
		if args[1] != nil {
			arg1 = args[1].(*fencev1.Entity)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDataStore_addEntity_Call) Return(err error) *MockDataStore_addEntity_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDataStore_addEntity_Call) RunAndReturn(run func(ctx context.Context, entity *fencev1.Entity) error) *MockDataStore_addEntity_Call {
	_c.Call.Return(run)
	return _c
}

// addPolicy provides a mock function for the type MockDataStore
func (_mock *MockDataStore) addPolicy(ctx context.Context, id string, content string) error {
	ret := _mock.Called(ctx, id, content)

	if len(ret) == 0 {
		panic("no return value specified for addPolicy")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, id, content)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDataStore_addPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'addPolicy'
type MockDataStore_addPolicy_Call struct {
	*mock.Call
}

// addPolicy is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - content string
func (_e *MockDataStore_Expecter) addPolicy(ctx interface{}, id interface{}, content interface{}) *MockDataStore_addPolicy_Call {
	return &MockDataStore_addPolicy_Call{Call: _e.mock.On("addPolicy", ctx, id, content)}
}

func (_c *MockDataStore_addPolicy_Call) Run(run func(ctx context.Context, id string, content string)) *MockDataStore_addPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDataStore_addPolicy_Call) Return(err error) *MockDataStore_addPolicy_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDataStore_addPolicy_Call) RunAndReturn(run func(ctx context.Context, id string, content string) error) *MockDataStore_addPolicy_Call {
	_c.Call.Return(run)
	return _c
}

// deleteEntity provides a mock function for the type MockDataStore
func (_mock *MockDataStore) deleteEntity(ctx context.Context, uid *fencev1.UID) error {
	ret := _mock.Called(ctx, uid)

	if len(ret) == 0 {
		panic("no return value specified for deleteEntity")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *fencev1.UID) error); ok {
		r0 = returnFunc(ctx, uid)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDataStore_deleteEntity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'deleteEntity'
type MockDataStore_deleteEntity_Call struct {
	*mock.Call
}

// deleteEntity is a helper method to define mock.On call
//   - ctx context.Context
//   - uid *fencev1.UID
func (_e *MockDataStore_Expecter) deleteEntity(ctx interface{}, uid interface{}) *MockDataStore_deleteEntity_Call {
	return &MockDataStore_deleteEntity_Call{Call: _e.mock.On("deleteEntity", ctx, uid)}
}

func (_c *MockDataStore_deleteEntity_Call) Run(run func(ctx context.Context, uid *fencev1.UID)) *MockDataStore_deleteEntity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *fencev1.UID
		if args[1] != nil {
			arg1 = args[1].(*fencev1.UID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDataStore_deleteEntity_Call) Return(err error) *MockDataStore_deleteEntity_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDataStore_deleteEntity_Call) RunAndReturn(run func(ctx context.Context, uid *fencev1.UID) error) *MockDataStore_deleteEntity_Call {
	_c.Call.Return(run)
	return _c
}

// deletePolicy provides a mock function for the type MockDataStore
func (_mock *MockDataStore) deletePolicy(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for deletePolicy")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDataStore_deletePolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'deletePolicy'
type MockDataStore_deletePolicy_Call struct {
	*mock.Call
}

// deletePolicy is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockDataStore_Expecter) deletePolicy(ctx interface{}, id interface{}) *MockDataStore_deletePolicy_Call {
	return &MockDataStore_deletePolicy_Call{Call: _e.mock.On("deletePolicy", ctx, id)}
}

func (_c *MockDataStore_deletePolicy_Call) Run(run func(ctx context.Context, id string)) *MockDataStore_deletePolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDataStore_deletePolicy_Call) Return(err error) *MockDataStore_deletePolicy_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDataStore_deletePolicy_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockDataStore_deletePolicy_Call {
	_c.Call.Return(run)
	return _c
}

// getEntities provides a mock function for the type MockDataStore
func (_mock *MockDataStore) getEntities(ctx context.Context) ([]*fencev1.Entity, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for getEntities")
	}

	var r0 []*fencev1.Entity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*fencev1.Entity, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*fencev1.Entity); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*fencev1.Entity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDataStore_getEntities_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getEntities'
type MockDataStore_getEntities_Call struct {
	*mock.Call
}

// getEntities is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDataStore_Expecter) getEntities(ctx interface{}) *MockDataStore_getEntities_Call {
	return &MockDataStore_getEntities_Call{Call: _e.mock.On("getEntities", ctx)}
}

func (_c *MockDataStore_getEntities_Call) Run(run func(ctx context.Context)) *MockDataStore_getEntities_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDataStore_getEntities_Call) Return(entitys []*fencev1.Entity, err error) *MockDataStore_getEntities_Call {
	_c.Call.Return(entitys, err)
	return _c
}

func (_c *MockDataStore_getEntities_Call) RunAndReturn(run func(ctx context.Context) ([]*fencev1.Entity, error)) *MockDataStore_getEntities_Call {
	_c.Call.Return(run)
	return _c
}

// getEntityMap provides a mock function for the type MockDataStore
func (_mock *MockDataStore) getEntityMap(ctx context.Context) (cedar.EntityMap, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for getEntityMap")
	}

	var r0 cedar.EntityMap
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (cedar.EntityMap, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) cedar.EntityMap); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(cedar.EntityMap)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDataStore_getEntityMap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getEntityMap'
type MockDataStore_getEntityMap_Call struct {
	*mock.Call
}

// getEntityMap is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDataStore_Expecter) getEntityMap(ctx interface{}) *MockDataStore_getEntityMap_Call {
	return &MockDataStore_getEntityMap_Call{Call: _e.mock.On("getEntityMap", ctx)}
}

func (_c *MockDataStore_getEntityMap_Call) Run(run func(ctx context.Context)) *MockDataStore_getEntityMap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDataStore_getEntityMap_Call) Return(v cedar.EntityMap, err error) *MockDataStore_getEntityMap_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockDataStore_getEntityMap_Call) RunAndReturn(run func(ctx context.Context) (cedar.EntityMap, error)) *MockDataStore_getEntityMap_Call {
	_c.Call.Return(run)
	return _c
}

// getPolicies provides a mock function for the type MockDataStore
func (_mock *MockDataStore) getPolicies(ctx context.Context) ([]*fencev1.Policy, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for getPolicies")
	}

	var r0 []*fencev1.Policy
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*fencev1.Policy, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*fencev1.Policy); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*fencev1.Policy)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDataStore_getPolicies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getPolicies'
type MockDataStore_getPolicies_Call struct {
	*mock.Call
}

// getPolicies is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDataStore_Expecter) getPolicies(ctx interface{}) *MockDataStore_getPolicies_Call {
	return &MockDataStore_getPolicies_Call{Call: _e.mock.On("getPolicies", ctx)}
}

func (_c *MockDataStore_getPolicies_Call) Run(run func(ctx context.Context)) *MockDataStore_getPolicies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDataStore_getPolicies_Call) Return(policys []*fencev1.Policy, err error) *MockDataStore_getPolicies_Call {
	_c.Call.Return(policys, err)
	return _c
}

func (_c *MockDataStore_getPolicies_Call) RunAndReturn(run func(ctx context.Context) ([]*fencev1.Policy, error)) *MockDataStore_getPolicies_Call {
	_c.Call.Return(run)
	return _c
}

// getPolicy provides a mock function for the type MockDataStore
func (_mock *MockDataStore) getPolicy(ctx context.Context, id string) (*cedar.Policy, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for getPolicy")
	}

	var r0 *cedar.Policy
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*cedar.Policy, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *cedar.Policy); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cedar.Policy)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDataStore_getPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getPolicy'
type MockDataStore_getPolicy_Call struct {
	*mock.Call
}

// getPolicy is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockDataStore_Expecter) getPolicy(ctx interface{}, id interface{}) *MockDataStore_getPolicy_Call {
	return &MockDataStore_getPolicy_Call{Call: _e.mock.On("getPolicy", ctx, id)}
}

func (_c *MockDataStore_getPolicy_Call) Run(run func(ctx context.Context, id string)) *MockDataStore_getPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDataStore_getPolicy_Call) Return(policy *cedar.Policy, err error) *MockDataStore_getPolicy_Call {
	_c.Call.Return(policy, err)
	return _c
}

func (_c *MockDataStore_getPolicy_Call) RunAndReturn(run func(ctx context.Context, id string) (*cedar.Policy, error)) *MockDataStore_getPolicy_Call {
	_c.Call.Return(run)
	return _c
}

// getPolicySet provides a mock function for the type MockDataStore
func (_mock *MockDataStore) getPolicySet(ctx context.Context) (*cedar.PolicySet, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for getPolicySet")
	}

	var r0 *cedar.PolicySet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*cedar.PolicySet, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *cedar.PolicySet); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cedar.PolicySet)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDataStore_getPolicySet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getPolicySet'
type MockDataStore_getPolicySet_Call struct {
	*mock.Call
}

// getPolicySet is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDataStore_Expecter) getPolicySet(ctx interface{}) *MockDataStore_getPolicySet_Call {
	return &MockDataStore_getPolicySet_Call{Call: _e.mock.On("getPolicySet", ctx)}
}

func (_c *MockDataStore_getPolicySet_Call) Run(run func(ctx context.Context)) *MockDataStore_getPolicySet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDataStore_getPolicySet_Call) Return(policySet *cedar.PolicySet, err error) *MockDataStore_getPolicySet_Call {
	_c.Call.Return(policySet, err)
	return _c
}

func (_c *MockDataStore_getPolicySet_Call) RunAndReturn(run func(ctx context.Context) (*cedar.PolicySet, error)) *MockDataStore_getPolicySet_Call {
	_c.Call.Return(run)
	return _c
}
