// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package client

import (
	"context"

	"github.com/binarymatt/fence/gen/fence/v1"
	mock "github.com/stretchr/testify/mock"
)

// NewMockFenceState creates a new instance of MockFenceState. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFenceState(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFenceState {
	mock := &MockFenceState{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFenceState is an autogenerated mock type for the FenceState type
type MockFenceState struct {
	mock.Mock
}

type MockFenceState_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFenceState) EXPECT() *MockFenceState_Expecter {
	return &MockFenceState_Expecter{mock: &_m.Mock}
}

// IsAllowed provides a mock function for the type MockFenceState
func (_mock *MockFenceState) IsAllowed(ctx context.Context, principal *fencev1.UID, action *fencev1.UID, resource *fencev1.UID) error {
	ret := _mock.Called(ctx, principal, action, resource)

	if len(ret) == 0 {
		panic("no return value specified for IsAllowed")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *fencev1.UID, *fencev1.UID, *fencev1.UID) error); ok {
		r0 = returnFunc(ctx, principal, action, resource)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFenceState_IsAllowed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsAllowed'
type MockFenceState_IsAllowed_Call struct {
	*mock.Call
}

// IsAllowed is a helper method to define mock.On call
//   - ctx context.Context
//   - principal *fencev1.UID
//   - action *fencev1.UID
//   - resource *fencev1.UID
func (_e *MockFenceState_Expecter) IsAllowed(ctx interface{}, principal interface{}, action interface{}, resource interface{}) *MockFenceState_IsAllowed_Call {
	return &MockFenceState_IsAllowed_Call{Call: _e.mock.On("IsAllowed", ctx, principal, action, resource)}
}

func (_c *MockFenceState_IsAllowed_Call) Run(run func(ctx context.Context, principal *fencev1.UID, action *fencev1.UID, resource *fencev1.UID)) *MockFenceState_IsAllowed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *fencev1.UID
		if args[1] != nil {
			arg1 = args[1].(*fencev1.UID)
		}
		var arg2 *fencev1.UID
		if args[2] != nil {
			arg2 = args[2].(*fencev1.UID)
		}
		var arg3 *fencev1.UID
		if args[3] != nil {
			arg3 = args[3].(*fencev1.UID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockFenceState_IsAllowed_Call) Return(err error) *MockFenceState_IsAllowed_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFenceState_IsAllowed_Call) RunAndReturn(run func(ctx context.Context, principal *fencev1.UID, action *fencev1.UID, resource *fencev1.UID) error) *MockFenceState_IsAllowed_Call {
	_c.Call.Return(run)
	return _c
}

// Refresh provides a mock function for the type MockFenceState
func (_mock *MockFenceState) Refresh(context1 context.Context) error {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for Refresh")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFenceState_Refresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Refresh'
type MockFenceState_Refresh_Call struct {
	*mock.Call
}

// Refresh is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockFenceState_Expecter) Refresh(context1 interface{}) *MockFenceState_Refresh_Call {
	return &MockFenceState_Refresh_Call{Call: _e.mock.On("Refresh", context1)}
}

func (_c *MockFenceState_Refresh_Call) Run(run func(context1 context.Context)) *MockFenceState_Refresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFenceState_Refresh_Call) Return(err error) *MockFenceState_Refresh_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFenceState_Refresh_Call) RunAndReturn(run func(context1 context.Context) error) *MockFenceState_Refresh_Call {
	_c.Call.Return(run)
	return _c
}

// refresh provides a mock function for the type MockFenceState
func (_mock *MockFenceState) refresh() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for refresh")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFenceState_refresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'refresh'
type MockFenceState_refresh_Call struct {
	*mock.Call
}

// refresh is a helper method to define mock.On call
func (_e *MockFenceState_Expecter) refresh() *MockFenceState_refresh_Call {
	return &MockFenceState_refresh_Call{Call: _e.mock.On("refresh")}
}

func (_c *MockFenceState_refresh_Call) Run(run func()) *MockFenceState_refresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFenceState_refresh_Call) Return(err error) *MockFenceState_refresh_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFenceState_refresh_Call) RunAndReturn(run func() error) *MockFenceState_refresh_Call {
	_c.Call.Return(run)
	return _c
}
